# Configurações do MySQL
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cuidaidoso
        username: root
        password: 1234
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
